version: '3.8'
services:
  bikeramp-postgres:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'bikeramp'
      POSTGRES_PASSWORD: 'bikeramp'
      POSTGRES_DB: 'bikeramp'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  bikeramp-api:
    build:
      context: .
    ports:
      - '3100:3100'
    environment:
      PORT: 3100
      TYPEORM_HOST: 'bikeramp-postgres'
      TYPEORM_USERNAME: 'bikeramp'
      TYPEORM_PASSWORD: 'bikeramp'
      TYPEORM_DATABASE: 'bikeramp'
      TYPEORM_PORT: '5432'
      TYPEORM_LOGGING: 'true'
      TYPEORM_MIGRATIONS_DIR: 'src/migrations'
      TYPEORM_MIGRATIONS_RUN: 'false'
      GOOGLE_MAPS_API_KEY: 'AIzaSyCGo1fflZ9-DqH_6yqSMqeA6GLHqK38w6o'
    volumes:
      - .:/code
    depends_on:
      - 'bikeramp-postgres'
