name: API CI

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: 'bikeramp-tests'
          postgresql user: 'bikeramp'
          postgresql password: 'bikeramp'

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: .

      - name: Run build
        working-directory: .
        run: yarn build

      - name: Run lint
        working-directory: .
        run: yarn lint

      - name: Run tests
        working-directory: .
        run: yarn test

      - name: Run e2e tests
        working-directory: .
        run: |
          cp .env.testing .env
          yarn test
